# Generated by Django 5.1.2 on 2025-10-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlecomment_delete_articlerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_cover_url',
            field=models.URLField(blank=True),
        ),
    ]
